{
 "title": "Logstash Heath",
 "tags": [ "logstash" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "HOST",
    "label": "HOST",
    "query": "tag_values(cpu_usage_system,host)"
   }
  ]
 },
 "panels": [
  { "title": "Base Resource -", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "- Logstash CPU %",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregator": "avg",
     "alias": "logstash process cpu percent",
     "currentFilterType": "literal_or",
     "currentTagKey": "node_name",
     "currentTagValue": "my_hostname1",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "prod",
       "groupBy": false,
       "tagk": "prodstatus",
       "type": "literal_or"
      },
      {
       "filter": "$HOST",
       "groupBy": false,
       "tagk": "host",
       "type": "literal_or"
      }
     ],
     "metric": "logstash_process_cpu_percent"
    }
   ]
  },
  {
   "title": "- Logstash CPU Load Average 1m",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregator": "avg",
     "alias": "logstash cpu load average 1m",
     "currentFilterKey": "host",
     "currentFilterType": "literal_or",
     "currentFilterValue": "$HOST",
     "currentTagKey": "node_name",
     "currentTagValue": "my_hostname1",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "downsampleInterval": "1m",
     "filters": [
      {
       "filter": "prod",
       "groupBy": false,
       "tagk": "prodstatus",
       "type": "literal_or"
      }
     ],
     "metric": "logstash_process_cpu_load_average_1m"
    }
   ]
  },
  {
   "title": "- JVM Mem Heap Used %",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregator": "avg",
     "alias": "jvm mem heap used percent",
     "currentFilterType": "literal_or",
     "currentTagKey": "node_name",
     "currentTagValue": "my_hostname1",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "downsampleInterval": "5m",
     "filters": [
      {
       "filter": "prod",
       "groupBy": false,
       "tagk": "prodstatus",
       "type": "literal_or"
      },
      {
       "filter": "$HOST",
       "groupBy": false,
       "tagk": "host",
       "type": "literal_or"
      }
     ],
     "metric": "logstash_jvm_mem_heap_used_percent"
    }
   ]
  },
  {
   "title": "- JVM Uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregator": "avg",
     "alias": "jvm uptime",
     "currentFilterType": "literal_or",
     "currentTagKey": "node_name",
     "currentTagValue": "my_hostname1",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "prod",
       "groupBy": false,
       "tagk": "prodstatus",
       "type": "literal_or"
      },
      {
       "filter": "$HOST",
       "groupBy": false,
       "tagk": "host",
       "type": "literal_or"
      }
     ],
     "metric": "logstash_jvm_uptime_in_millis"
    }
   ]
  },
  { "title": "Logstash Events -", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "- Events In",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "aggregator": "avg",
     "alias": "Events In /sec",
     "currentFilterType": "literal_or",
     "currentTagKey": "node_name",
     "currentTagValue": "my_hostname1",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "downsampleInterval": "1m",
     "filters": [
      {
       "filter": "prod",
       "groupBy": false,
       "tagk": "prodstatus",
       "type": "literal_or"
      },
      {
       "filter": "$HOST",
       "groupBy": false,
       "tagk": "host",
       "type": "literal_or"
      }
     ],
     "metric": "logstash_events_in"
    }
   ]
  },
  {
   "title": "- Events Filtered",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 4, "x": 4, "y": 7 },
   "targets": [
    {
     "aggregator": "avg",
     "alias": "Events Filtered /sec",
     "currentFilterType": "literal_or",
     "currentTagKey": "node_name",
     "currentTagValue": "my_hostname1",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "downsampleInterval": "1m",
     "filters": [
      {
       "filter": "prod",
       "groupBy": false,
       "tagk": "prodstatus",
       "type": "literal_or"
      },
      {
       "filter": "$HOST",
       "groupBy": false,
       "tagk": "host",
       "type": "literal_or"
      }
     ],
     "metric": "logstash_events_filtered"
    }
   ]
  },
  {
   "title": "- Events Out",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 4, "x": 8, "y": 7 },
   "targets": [
    {
     "aggregator": "avg",
     "alias": "Events Out /sec",
     "currentFilterType": "literal_or",
     "currentTagKey": "node_name",
     "currentTagValue": "my_hostname1",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "downsampleInterval": "1m",
     "filters": [
      {
       "filter": "prod",
       "groupBy": false,
       "tagk": "prodstatus",
       "type": "literal_or"
      },
      {
       "filter": "$HOST",
       "groupBy": false,
       "tagk": "host",
       "type": "literal_or"
      }
     ],
     "metric": "logstash_events_out"
    }
   ]
  },
  {
   "title": "- Event Duration",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 4, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "aggregator": "avg",
     "alias": "Events Duration / ms",
     "currentFilterType": "literal_or",
     "currentTagKey": "node_name",
     "currentTagValue": "my_hostname1",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "downsampleInterval": "1m",
     "filters": [
      {
       "filter": "prod",
       "groupBy": false,
       "tagk": "prodstatus",
       "type": "literal_or"
      },
      {
       "filter": "$HOST",
       "groupBy": false,
       "tagk": "host",
       "type": "literal_or"
      }
     ],
     "metric": "logstash_events_duration_in_millis"
    }
   ]
  },
  {
   "title": "- Event queue push duration",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 4, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "aggregator": "avg",
     "alias": "Events Queue Push Duration / ms",
     "currentFilterType": "literal_or",
     "currentTagKey": "node_name",
     "currentTagValue": "my_hostname1",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "downsampleInterval": "1m",
     "filters": [
      {
       "filter": "prod",
       "groupBy": false,
       "tagk": "prodstatus",
       "type": "literal_or"
      },
      {
       "filter": "$HOST",
       "groupBy": false,
       "tagk": "host",
       "type": "literal_or"
      }
     ],
     "metric": "logstash_events_queue_push_duration_in_millis"
    }
   ]
  },
  { "title": "Logstash Queue Events", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "- Queue Events [$HOST]",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 20, "x": 0, "y": 20 },
   "targets": [
    {
     "aggregator": "avg",
     "alias": "$HOST",
     "currentFilterType": "literal_or",
     "currentTagKey": "node_name",
     "currentTagValue": "my_hostname1",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "prod",
       "groupBy": false,
       "tagk": "prodstatus",
       "type": "literal_or"
      },
      {
       "filter": "$HOST",
       "groupBy": false,
       "tagk": "host",
       "type": "regexp"
      }
     ],
     "metric": "logstash_queue_events"
    }
   ]
  },
  {
   "title": "Logstash Queue Events [ comparison with all nodes ] -",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 }
  },
  {
   "title": "- Queue Events [All nodes]",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 20, "x": 0, "y": 32 },
   "targets": [
    {
     "aggregator": "avg",
     "alias": "$tag_host",
     "currentFilterType": "literal_or",
     "currentTagKey": "node_name",
     "currentTagValue": "my_hostname1",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "prod",
       "groupBy": false,
       "tagk": "prodstatus",
       "type": "literal_or"
      },
      {
       "filter": "*",
       "groupBy": true,
       "tagk": "host",
       "type": "wildcard"
      }
     ],
     "metric": "logstash_queue_events"
    }
   ]
  },
  { "title": "JVM Stats -", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "- JVM Heap Usage in %",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 4, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "aggregator": "sum",
     "alias": "Heap Usage in %",
     "currentFilterType": "literal_or",
     "currentTagKey": "node_name",
     "currentTagValue": "my_hostname1",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "prod",
       "groupBy": false,
       "tagk": "prodstatus",
       "type": "literal_or"
      },
      {
       "filter": "$HOST",
       "groupBy": false,
       "tagk": "host",
       "type": "literal_or"
      }
     ],
     "metric": "logstash_jvm_mem_heap_used_percent"
    }
   ]
  },
  {
   "title": "- JVM Heap Usage in Bytes",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 4, "x": 4, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "aggregator": "avg",
     "alias": "Heap Max",
     "currentFilterType": "literal_or",
     "currentTagKey": "node_name",
     "currentTagValue": "my_hostname1",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "prod",
       "groupBy": false,
       "tagk": "prodstatus",
       "type": "literal_or"
      },
      {
       "filter": "$HOST",
       "groupBy": false,
       "tagk": "host",
       "type": "literal_or"
      }
     ],
     "metric": "logstash_jvm_mem_heap_max_in_bytes"
    },
    {
     "aggregator": "avg",
     "alias": "Heap Used",
     "currentFilterType": "literal_or",
     "currentTagKey": "node_name",
     "currentTagValue": "my_hostname1",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "prod",
       "groupBy": false,
       "tagk": "prodstatus",
       "type": "literal_or"
      },
      {
       "filter": "$HOST",
       "groupBy": false,
       "tagk": "host",
       "type": "literal_or"
      }
     ],
     "metric": "logstash_jvm_mem_heap_used_in_bytes"
    }
   ]
  },
  {
   "title": "- JVM Garbage Collection Count",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 4, "x": 8, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "aggregator": "avg",
     "alias": "GC Young",
     "currentFilterType": "literal_or",
     "currentTagKey": "node_name",
     "currentTagValue": "my_hostname1",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "prod",
       "groupBy": false,
       "tagk": "prodstatus",
       "type": "literal_or"
      },
      {
       "filter": "$HOST",
       "groupBy": false,
       "tagk": "host",
       "type": "literal_or"
      }
     ],
     "metric": "logstash_jvm_gc_collectors_young_collection_count"
    },
    {
     "aggregator": "avg",
     "alias": "GC Old",
     "currentFilterType": "literal_or",
     "currentTagKey": "node_name",
     "currentTagValue": "my_hostname1",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "prod",
       "groupBy": false,
       "tagk": "prodstatus",
       "type": "literal_or"
      },
      {
       "filter": "$HOST",
       "groupBy": false,
       "tagk": "host",
       "type": "literal_or"
      }
     ],
     "metric": "logstash_jvm_gc_collectors_old_collection_count"
    }
   ]
  },
  {
   "title": "- JVM Garbage Collection Time in ms",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 4, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "aggregator": "avg",
     "alias": "GC Young Time",
     "currentFilterType": "literal_or",
     "currentTagKey": "node_name",
     "currentTagValue": "my_hostname1",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "prod",
       "groupBy": false,
       "tagk": "prodstatus",
       "type": "literal_or"
      },
      {
       "filter": "$HOST",
       "groupBy": false,
       "tagk": "host",
       "type": "literal_or"
      }
     ],
     "metric": "logstash_jvm_gc_collectors_young_collection_time_in_millis"
    },
    {
     "aggregator": "avg",
     "alias": "GC Old Time",
     "currentFilterType": "literal_or",
     "currentTagKey": "node_name",
     "currentTagValue": "my_hostname1",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "prod",
       "groupBy": false,
       "tagk": "prodstatus",
       "type": "literal_or"
      },
      {
       "filter": "$HOST",
       "groupBy": false,
       "tagk": "host",
       "type": "literal_or"
      }
     ],
     "metric": "logstash_jvm_gc_collectors_old_collection_time_in_millis"
    }
   ]
  },
  {
   "title": "- JVM Threads Count",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 4, "x": 16, "y": 45 },
   "targets": [
    {
     "aggregator": "avg",
     "alias": "jvm threads count",
     "currentFilterType": "literal_or",
     "currentTagKey": "node_name",
     "currentTagValue": "my_hostname1",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "prod",
       "groupBy": false,
       "tagk": "prodstatus",
       "type": "literal_or"
      },
      {
       "filter": "$HOST",
       "groupBy": false,
       "tagk": "host",
       "type": "literal_or"
      }
     ],
     "metric": "logstash_jvm_threads_count"
    }
   ]
  },
  { "title": "CPU and Descriptors -", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "title": "- Logstash Process CPU %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "aggregator": "sum",
     "alias": "Logstash Process CPU Percent",
     "currentFilterType": "literal_or",
     "currentTagKey": "node_name",
     "currentTagValue": "my_hostname1",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "prod",
       "groupBy": false,
       "tagk": "prodstatus",
       "type": "literal_or"
      },
      {
       "filter": "$HOST",
       "groupBy": false,
       "tagk": "host",
       "type": "literal_or"
      }
     ],
     "metric": "logstash_process_cpu_percent"
    }
   ]
  },
  {
   "title": "- Process File Descriptors",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 58 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregator": "avg",
     "alias": "max file descriptors",
     "currentFilterType": "literal_or",
     "currentTagKey": "node_name",
     "currentTagValue": "my_hostname1",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "downsampleInterval": "5m",
     "filters": [
      {
       "filter": "prod",
       "groupBy": false,
       "tagk": "prodstatus",
       "type": "literal_or"
      },
      {
       "filter": "$HOST",
       "groupBy": false,
       "tagk": "host",
       "type": "literal_or"
      }
     ],
     "metric": "logstash_process_max_file_descriptors"
    },
    {
     "aggregator": "avg",
     "alias": "open file descriptors",
     "currentFilterType": "literal_or",
     "currentTagKey": "node_name",
     "currentTagValue": "my_hostname1",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "downsampleInterval": "5m",
     "filters": [
      {
       "filter": "prod",
       "groupBy": false,
       "tagk": "prodstatus",
       "type": "literal_or"
      },
      {
       "filter": "$HOST",
       "groupBy": false,
       "tagk": "host",
       "type": "literal_or"
      }
     ],
     "metric": "logstash_process_open_file_descriptors"
    }
   ]
  }
 ]
}